FROM python:3.9-slim

WORKDIR /consciousness

COPY . /consciousness/

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8004

ENV PORT=8004
ENV PYTHONPATH=/consciousness
ENV ASSETS_PATH=/consciousness/assets

# Run the application
CMD ["uvicorn", "consciousness.main:app", "--host", "0.0.0.0", "--port", "8004", "--reload"]
